/*
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test1', 'asdfghj dfghjk', 1, 0, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test2', 'zzzzhjsdsodj  nikuoioiu o', 1, 1, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test3', 'djjsjsd jakjsajk akjakak', 1, null, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test4', 'jasjsja asjkakjs kj kkaskas', 1, null, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test5', 'sdfghj fghjtyu', 1, null, 0, 0);
*/
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('Map center', 'Nothing wrong here. Just marking one location', 1, null, 60.440963, 22.25122);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('Turku market squary', 'Please, do not crash on market stalls!', 1, null, 60.45158864063455, 22.267062552273277);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('The WaterLoo', 'Please, no bikes inside', 1, null, 60.45520749649627, 22.269111759960655);

