INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test1', 'asdfghj dfghjk', 1, 0, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test2', 'zzzzhjsdsodj  nikuoioiu o', 1, 1, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test3', 'djjsjsd jakjsajk akjakak', 1, null, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test4', 'jasjsja asjkakjs kj kkaskas', 1, null, 0, 0);
INSERT INTO PUBLIC.ITEMS (TITLE, DESCRIPTION, OPTLOCK, USER_ID, LAT, LONG) VALUES ('test5', 'sdfghj fghjtyu', 1, null, 0, 0);